# Generated by Django 2.1.2 on 2018-10-23 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nominee',
            name='reason_for_nomination',
            field=models.TextField(null=True),
        ),
    ]
