# Generated by Django 2.1.2 on 2018-10-23 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181023_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nominee',
            name='reason_for_nomination',
            field=models.TextField(default=None, null=True),
        ),
    ]
