# Generated by Django 2.1.2 on 2018-10-23 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181023_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominee',
            name='creator',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='nominee',
            name='reason_for_nomination',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
