# Generated by Django 2.1.2 on 2018-12-04 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20181023_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominee',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
